config/routes.rb
  
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end
  
  resources :friends
  get 'demo/mailbox'

  resources :links

  root 'welcome#index'

  resources :articles do
    member do
      get 'search'
    end
  end
  resources :categories

  resources :shipment_lines
  resources :shipments
  resources :shipments
  resources :addresses
  resources :people
  get '/flights/:flight_id/seats' =>"seats#flight_seats"
  
  resources :menu_items
  resources :menus
  resources :seats
  resources :flights

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to  :person, inverse_of: :address
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :articleCategories
  has_many :categories, through: :articleCategories
  
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
  validates :categories, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articleCategories
  has_many :articles, through: :articleCategories
  
  has_many :links
  
	validates_uniqueness_of :name
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :shipment
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many  :orders, inverse_of: :customer
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  has_many :seats, dependent: :destroy
  
  accepts_nested_attributes_for :seats
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  validates :name, presence: true
  validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }
    
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :category
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many  :menuItems
  
  around_create :my_create_check
  
  after_initialize do |menu|
    puts "You have initialized an object!"
  end
 
  after_find do |menu|
    puts "You have found an object!"
  end
  
  protected
    def my_create_check
      puts "around_create an Menu object"
    end
  
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
  validate :check_capicity
  
  private
    def check_capicity
      if menu.menuItems.size > menu.capacity
        errors.add(:name,"You can not add more than #{menu.capacity} menu items")
      end
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to  :customer, inverse_of: :orders
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :addresses, inverse_of: :person
  accepts_nested_attributes_for :addresses
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :flight
  validate :check_booking
  
  private
    def check_booking
      if !flight.nil?  && baggage > flight.baggage_allowance
        errors.add(:baggage, "You have too much baggage")
      end
      
      if !flight.nil?  && flight.seats.size >= flight.capacity
        errors.add(:name,"The flight is fully booked")
      end
    end
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  has_many  :shipmentLines, dependent: :destroy
  has_many  :charges, dependent: :destroy
  accepts_nested_attributes_for :shipmentLines, :charges
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:name, :avatar)
    end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend, :multipart => true) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="friend" id="<%= friend.id %>">
  <div class="front">
    <%= link_to friend, class: 'pic-link' do %>
      <%= image_tag friend.avatar.url(:square) %>
    <% end %>
  </div>

  <div class="back">
    <span class="friend-name"><%= friend.name %></span>
    <div class="actions">
      <%= link_to 'Show', friend %>
      <%= link_to 'Edit', edit_friend_path(friend) %>
      <%= link_to 'Delete', friend, confirm: 'Are you sure you want to lose a friend?', method: :delete, class: 'destroy' %>
    </div>
  </div>
</div>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>
<h2>Make a new friend <%= link_to 'New Friend', new_friend_path, class: 'new-friend' %></h2>

<h1>Listing Friends</h1>
<section id="friends">
  <%= render @friends%>
</section>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>
<%= image_tag @friend.avatar.url%>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>