config/routes.rb
  
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end
  
  resources :friends
  get 'demo/mailbox'

  resources :links

  root 'welcome#index'

  resources :articles do
    member do
      get 'search'
    end
  end
  resources :categories

  resources :shipment_lines
  resources :shipments
  resources :shipments
  resources :addresses
  resources :people
  get '/flights/:flight_id/seats' =>"seats#flight_seats"
  
  resources :menu_items
  resources :menus
  resources :seats
  resources :flights

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to  :person, inverse_of: :address
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :articleCategories
  has_many :categories, through: :articleCategories
  
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
  validates :categories, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articleCategories
  has_many :articles, through: :articleCategories
  
  has_many :links
  
	validates_uniqueness_of :name
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :shipment
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many  :orders, inverse_of: :customer
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  has_many :seats, dependent: :destroy
  
  accepts_nested_attributes_for :seats
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  validates :name, presence: true
  validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }
    
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :category
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many  :menuItems
  
  around_create :my_create_check
  
  after_initialize do |menu|
    puts "You have initialized an object!"
  end
 
  after_find do |menu|
    puts "You have found an object!"
  end
  
  protected
    def my_create_check
      puts "around_create an Menu object"
    end
  
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
  validate :check_capicity
  
  private
    def check_capicity
      if menu.menuItems.size > menu.capacity
        errors.add(:name,"You can not add more than #{menu.capacity} menu items")
      end
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to  :customer, inverse_of: :orders
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :addresses, inverse_of: :person
  accepts_nested_attributes_for :addresses
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :flight
  validate :check_booking
  
  private
    def check_booking
      if !flight.nil?  && baggage > flight.baggage_allowance
        errors.add(:baggage, "You have too much baggage")
      end
      
      if !flight.nil?  && flight.seats.size >= flight.capacity
        errors.add(:name,"The flight is fully booked")
      end
    end
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  has_many  :shipmentLines, dependent: :destroy
  has_many  :charges, dependent: :destroy
  accepts_nested_attributes_for :shipmentLines, :charges
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @recent_articles = Article.all.last(5)
  end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_function_index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Functionalities</h3>
  </div>
  <div class="panel-body">
    <div class="list-group">
      <%= link_to 'Addresses', addresses_path,  class:"list-group-item" %>
      <%= link_to 'Articles', articles_path,  class:"list-group-item" %>
      <%= link_to 'Categories', categories_path,  class:"list-group-item" %>
      <%= link_to 'Flights', flights_path,   class:"list-group-item" %>
      <%= link_to 'Menus', menus_path,   class:"list-group-item" %>
      <%= link_to 'Shipments', shipments_path,   class:"list-group-item" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welecome to Midi's Rails Lab</h1>
<%= render 'function_index'%>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Recent articles.</h3>
  </div>
  <div class="panel-body">
    <div class="list-group">
    <% @recent_articles.each do |article| %>
        <h1><%= link_to article.title, article, class:"list-group-item" %> </h1>
        <p>Posted at:<%= article.created_at.strftime('%b %d, %Y')%></p>
          <% article.categories.each do |category| %>
            <%= link_to category.name, category %> 
          <% end %>
          <br>
        <br>
        <p><%= truncate(article.content, length:300)%></p>
        <br>
        <br>
        <br>
        <br>
    <% end %>
    </div>
  </div>
</div>  