config/routes.rb
  
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end
  
  resources :friends
  get 'demo/mailbox'

  resources :links

  root 'welcome#index'

  resources :articles do
    member do
      get 'search'
    end
  end
  resources :categories

  resources :shipment_lines
  resources :shipments
  resources :shipments
  resources :addresses
  resources :people
  get '/flights/:flight_id/seats' =>"seats#flight_seats"
  
  resources :menu_items
  resources :menus
  resources :seats
  resources :flights

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to  :person, inverse_of: :address
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :articleCategories
  has_many :categories, through: :articleCategories
  
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
  validates :categories, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articleCategories
  has_many :articles, through: :articleCategories
  
  has_many :links
  
	validates_uniqueness_of :name
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :shipment
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many  :orders, inverse_of: :customer
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  has_many :seats, dependent: :destroy
  
  accepts_nested_attributes_for :seats
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  validates :name, presence: true
  validates :avatar,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ },
    attachment_size: { less_than: 5.megabytes }
    
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :category
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many  :menuItems
  
  around_create :my_create_check
  
  after_initialize do |menu|
    puts "You have initialized an object!"
  end
 
  after_find do |menu|
    puts "You have found an object!"
  end
  
  protected
    def my_create_check
      puts "around_create an Menu object"
    end
  
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  belongs_to :menu
  validate :check_capicity
  
  private
    def check_capicity
      if menu.menuItems.size > menu.capacity
        errors.add(:name,"You can not add more than #{menu.capacity} menu items")
      end
    end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to  :customer, inverse_of: :orders
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :addresses, inverse_of: :person
  accepts_nested_attributes_for :addresses
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :flight
  validate :check_booking
  
  private
    def check_booking
      if !flight.nil?  && baggage > flight.baggage_allowance
        errors.add(:baggage, "You have too much baggage")
      end
      
      if !flight.nil?  && flight.seats.size >= flight.capacity
        errors.add(:name,"The flight is fully booked")
      end
    end
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  has_many  :shipmentLines, dependent: :destroy
  has_many  :charges, dependent: :destroy
  accepts_nested_attributes_for :shipmentLines, :charges
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :set_shipment, only: [:show, :edit, :update, :destroy]

  # GET /shipments
  # GET /shipments.json
  def index
    @shipments = Shipment.all
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
    3.times {@shipment.shipmentLines.build}
    @shipment.charges.build
    
  end

  # GET /shipments/1/edit
  def edit
  end

  # POST /shipments
  # POST /shipments.json
  def create
    @shipment = Shipment.new(shipment_params)
    
    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: 'Shipment was successfully created.' }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to @shipment, notice: 'Shipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipment }
      else
        format.html { render :edit }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.html { redirect_to shipments_url, notice: 'Shipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:customer_name, shipmentLines_attributes:[:id, :line_no, :item_id, :quantity], charges_attributes:[:id,:carrier_account,:freight_term,:estimated_shipment_charge,:actual_shipment_charge,:freight_charge])
    end
    
    
    
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/shipments/_form.html.erb
<%= form_for(@shipment) do |f| %>
  <% if @shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% @shipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <br/>
  <p><strong>Lines</strong></p> 
  <table class="table table-striped">
    <thead>
      <tr>
        <td>line_no </td>
        <td>item_id </td>
        <td>quantity</td>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for :shipmentLines do |lines_form| %>
        <tr>
          <td><%= lines_form.text_field :line_no %></td>
          <td><%= lines_form.text_field :item_id %></td>
          <td><%= lines_form.text_field :quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
 <p>Charges</p>
 
  <%= f.fields_for :charges do |charges_form| %>
      <%= charges_form.label :carrier_account %>
      <%= charges_form.text_field :carrier_account %><br/>
      <%= charges_form.label :freight_term %>
      <%= charges_form.text_field :freight_term %><br/>
      <%= charges_form.label :estimated_shipment_charge %>
      <%= charges_form.number_field :estimated_shipment_charge %><br/>
      <%= charges_form.label :actual_shipment_charge %>
      <%= charges_form.number_field :actual_shipment_charge %><br/>
      <%= charges_form.label :freight_charge %>
      <%= charges_form.text_field :freight_charge %>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipments/edit.html.erb
<h1>Editing Shipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipment %> |
<%= link_to 'Back', shipments_path %>

app/views/shipments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shipments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Customer name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <td><%= shipment.customer_name %></td>
        <td><%= link_to 'Show', shipment %></td>
        <td><%= link_to 'Edit', edit_shipment_path(shipment) %></td>
        <td><%= link_to 'Destroy', shipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipment', new_shipment_path %>

app/views/shipments/new.html.erb
<h1>New Shipment</h1>

<%= render 'form' %>

<%= link_to 'Back', shipments_path %>

app/views/shipments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Customer name:</strong>
  <%= @shipment.customer_name %>
</p>
<p><strong>Lines</strong></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>line_no</th>
      <th>|item_id</th>
      <th>|quantity</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= @shipment.shipmentLines.each do |shipmentLine| %>
      <tr>
        <td><%= shipmentLine.line_no %></td>
        <td><%= shipmentLine.item_id %></td>
        <td><%= shipmentLine.quantity %></td>
        <td><%= link_to 'Show', shipmentLine %></td>
        <td><%= link_to 'Edit', edit_shipment_line_path(shipmentLine) %></td>
        <td><%= link_to 'Destroy', shipmentLine, method: :delete, data:{ confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><strong>Charges</strong></p>    
<table class="table table-striped">
  <thead>
    <tr>
      <th>carrier_account</th>
      <th>|freight_term</th>
      <th>|estimated_shipment_charge</th>
      <th>|actual_shipment_charge</th>
      <th>|freight_charge</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= @shipment.charges.each do |charge| %>
      <tr>
        <td><%= charge.carrier_account %></td>
        <td><%= charge.freight_term %></td>
        <td><%= charge.estimated_shipment_charge %></td>
        <td><%= charge.actual_shipment_charge %></td>
        <td><%= charge.freight_charge %></td>
        <td><%#= link_to 'Show', charge %></td>
        <td><%#= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%#= link_to 'Destroy', charge, method: :delete, data:{ confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  

<%= link_to 'Edit', edit_shipment_path(@shipment) %> |
<%= link_to 'Back', shipments_path %>